// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {scanner} from '../models';

export function ScanProject(arg1:string):Promise<scanner.ScanResult>;

export function SelectProject():Promise<Record<string, string>>;
