// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {scanner} from '../models';
import {history} from '../models';

export function CleanFiles(arg1:string,arg2:string,arg3:Array<string>):Promise<number>;

export function GetAIInsights(arg1:scanner.ScanResult):Promise<string>;

export function GetHistory():Promise<Array<history.ActionHistory>>;

export function ScanProject(arg1:string):Promise<scanner.ScanResult>;

export function SelectProject():Promise<Record<string, string>>;
