// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['CleanFiles'](arg1, arg2, arg3);
}

export function GetAIInsights(arg1) {
  return window['go']['main']['App']['GetAIInsights'](arg1);
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function ScanProject(arg1) {
  return window['go']['main']['App']['ScanProject'](arg1);
}

export function SelectProject() {
  return window['go']['main']['App']['SelectProject']();
}
